<a href="https://colab.research.google.com/github/MAI-AIIU/deep-learning/blob/main/src/first-week/data-preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Metadata
**Name**  
> Naveed Ahmad Hematmal

**Assignment**    

> Data preprocessing

## 1: Loading [UCI Abalone](https://archive.ics.uci.edu/dataset/1/abalone) dataset into pandas

In [6]:
import pandas as pd

# The `abalone.data` file have only data without headings, so we need to set column names manually
columns = [
    "Sex",
    "Length",
    "Diameter",
    "Height",
    "Whole_weight",
    "Shucked_weight",
    "Viscera_weight",
    "Shell_weight",
    "Rings"
]

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"

df = pd.read_csv(url, names=columns)

In [7]:
df.head()

,Sex,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

### Looking for Null and NaN values

In [8]:
df.isnull().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole_weight      0
Shucked_weight    0
Viscera_weight    0
Shell_weight      0
Rings             0
dtype: int64

In [9]:
df.isna().sum()

Sex               0
Length            0
Diameter          0
Height            0
Whole_weight      0
Shucked_weight    0
Viscera_weight    0
Shell_weight      0
Rings             0
dtype: int64

In [11]:
missing_rows = df.isna().any(axis=1).sum()
missing_rows

np.int64(0)

### Column Types

In [17]:
numerical = df.select_dtypes(include="number").columns
categorical = df.select_dtypes(include=["object", "category"]).columns

print("Numerical:", list(numerical))
print("Categorical:", list(categorical))

print("Numerical fraction:", round(len(numerical) / df.shape[1], 2))
print("Categorical fraction:", round(len(categorical) / df.shape[1], 2))

Numerical: ['Length', 'Diameter', 'Height', 'Whole_weight', 'Shucked_weight', 'Viscera_weight', 'Shell_weight', 'Rings']
Categorical: ['Sex']
Numerical fraction: 0.89
Categorical fraction: 0.11

## 2: Indexing by name

We can select columns by index-number, but using name is a safe way. Cause if we use number and then we change the column order our code will break.

In [18]:
# Select one column by name
df["Sex"]

0       M
1       M
2       F
3       M
4       I
       ..
4172    F
4173    M
4174    M
4175    F
4176    M
Name: Sex, Length: 4177, dtype: object

In [19]:
# Select multiple columns by names
df[["Length", "Diameter", "Rings"]]

      Length  Diameter  Rings
0      0.455     0.365     15
1      0.350     0.265      7
2      0.530     0.420      9
3      0.440     0.365     10
4      0.330     0.255      7
...      ...       ...    ...
4172   0.565     0.450     11
4173   0.590     0.440     10
4174   0.600     0.475      9
4175   0.625     0.485     10
4176   0.710     0.555     12

[4177 rows x 3 columns]

In [20]:
# Selecting column using loc function
df.loc[:, ["Sex", "Length", "Diameter"]]

     Sex  Length  Diameter
0      M   0.455     0.365
1      M   0.350     0.265
2      F   0.530     0.420
3      M   0.440     0.365
4      I   0.330     0.255
...   ..     ...       ...
4172   F   0.565     0.450
4173   M   0.590     0.440
4174   M   0.600     0.475
4175   F   0.625     0.485
4176   M   0.710     0.555

[4177 rows x 3 columns]

In [21]:
# Selecting specific columns with specific rows using loc function
df.loc[0:4, ["Sex", "Length", "Rings"]]

  Sex  Length  Rings
0   M   0.455     15
1   M   0.350      7
2   F   0.530      9
3   M   0.440     10
4   I   0.330      7

In [22]:
# Selecting specific columns with filter on rows using loc function
df.loc[df["Sex"] == "M", ["Length", "Diameter", "Rings"]]

      Length  Diameter  Rings
0      0.455     0.365     15
1      0.350     0.265      7
3      0.440     0.365     10
8      0.475     0.370      9
11     0.430     0.350     10
...      ...       ...    ...
4170   0.550     0.430     10
4171   0.560     0.430      8
4173   0.590     0.440     10
4174   0.600     0.475      9
4176   0.710     0.555     12

[1528 rows x 3 columns]